### ISSUE TITLE
we need to secure decent copies of these logos

### ISSUE THREAD

**Issue by barryrawn** [IEEE-PES-IAS-PowerAfrica-Conference/kigali-2022-event-management#12]
... and store here:

https://drive.google.com/drive/folders/1iWNGdnnoHsZcGSc9wocLO91vce1yK1gW

- [ ] IEEE PES
- [ ] IEEE smart village
- [ ] IEEE Africa Council
- [ ] PES & IAS
- [ ] IEEE Kenya Section

**Comment by chelangatk** [comment]
@barryrawn please give me access to the Google drive folder so I can upload the PAC png and psd logos, but alternatively they are accessible through this link https://drive.google.com/file/d/1jkaUwVu-36FvYjkE5iANquzojTKZX6WI/view?usp=sharing

**Comment by barryrawn** [comment]
Ah makes sense. Now your ieee e-mail address has been added, let me know if you have any difficulty accessing.

**Comment by chelangatk** [comment]
@barryrawn got access now @Cyiza-augustin ALL logos requested above updated in the folder https://drive.google.com/drive/folders/1iWNGdnnoHsZcGSc9wocLO91vce1yK1gW

**Comment by barryrawn** [comment]
Great, Mercy! Thank you!  I'll go ahead and close this issue.
